quarkus:
  log:
    level: INFO
    console:
      json:
        enabled: false
      stderr: true
  package:
    output-name: lg4c
    jar:
      add-runner-suffix: false
  native:
    resources:
      includes: META-INF/banner.txt
  banner:
    path: banner.txt
