@startuml
'https://plantuml.com/sequence-diagram
participant mac_os as os
participant lg4c as l
participant codex as c
participant lark_server as ls
autonumber
os -> l: start
l -> os: check codex
alt codex not exists
    l -> os: print error log and exit
else
    l -> c: Try connect mcp server
    alt mcp server exists
        l -> ls: Try connect websocket
        alt websocket exists
            l -> os: ready
        else
            l -> os: print error log and exit
        end
    else
        l -> os: Ask user to get file path for codex
        os --> l: user input file path
        l -> c: Try start mcp server
        l -> l: create AGENT.md in current directory \n and inject default prompt.
    end
end

@enduml
