@startuml
'https://plantuml.com/sequence-diagram
actor user as u
participant lark_server as ls
participant lg4c as l
participant codex as c
participant mac_os as os

autonumber
u -> ls: send message through robot
ls -> l: push message to lg4c
l -> l: parse message
l -> os: create folder in ~/.lg4c by date
l -> os: create record in ~/.lg4c/date_folder by user
l -> os: write message in ~/.lg4c/date_folder/user.md
l -> c: send message to codex
c --> l: receive thinking from codex
l -> os: write thinking in ~/.lg4c/date_folder/user.md
l --> ls: send back answer
ls --> u: receive answer from robot
@enduml
